In [1]:
from mxnet import nd

In [2]:
x = nd.array([3.0])
y = nd.array([2.0])

print('x + y =', x + y)
print('x * y =', x * y)
print('x / y =', x / y)
print('x ** y =', nd.power(x, y))

x + y = 
[5.]
<NDArray 1 @cpu(0)>
x * y = 
[6.]
<NDArray 1 @cpu(0)>
x / y = 
[1.5]
<NDArray 1 @cpu(0)>
x ** y = 
[9.]
<NDArray 1 @cpu(0)>


In [3]:
x.asscalar()

3.0

In [4]:
x = nd.arange(4)
print('x =', x)

x = 
[0. 1. 2. 3.]
<NDArray 4 @cpu(0)>


In [5]:
x[3]


[3.]
<NDArray 1 @cpu(0)>

In [6]:
x.shape

(4,)

In [7]:
a = 2
x = nd.array([1, 2, 3])
y = nd.array([10, 20, 30])
print(a * x)
print(a * x + y)


[2. 4. 6.]
<NDArray 3 @cpu(0)>

[12. 24. 36.]
<NDArray 3 @cpu(0)>


In [8]:
A = nd.arange(20).reshape((5, 4))
print(A)


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]
 [16. 17. 18. 19.]]
<NDArray 5x4 @cpu(0)>


In [9]:
print(A.T)


[[ 0.  4.  8. 12. 16.]
 [ 1.  5.  9. 13. 17.]
 [ 2.  6. 10. 14. 18.]
 [ 3.  7. 11. 15. 19.]]
<NDArray 4x5 @cpu(0)>


In [10]:
X = nd.arange(24).reshape((2, 3, 4))
print('X.shape =', X.shape)
print('X =', X)

X.shape = (2, 3, 4)
X = 
[[[ 0.  1.  2.  3.]
  [ 4.  5.  6.  7.]
  [ 8.  9. 10. 11.]]

 [[12. 13. 14. 15.]
  [16. 17. 18. 19.]
  [20. 21. 22. 23.]]]
<NDArray 2x3x4 @cpu(0)>


In [11]:
a = 2
x = nd.ones(3)
y = nd.zeros(3)
print(x.shape)
print(y.shape)
print((a * x).shape)
print((a * x + y).shape)

(3,)
(3,)
(3,)
(3,)


In [12]:
print(x)
print(nd.sum(x))


[1. 1. 1.]
<NDArray 3 @cpu(0)>

[3.]
<NDArray 1 @cpu(0)>


In [13]:
print(A)
print(nd.sum(A))


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]
 [16. 17. 18. 19.]]
<NDArray 5x4 @cpu(0)>

[190.]
<NDArray 1 @cpu(0)>


In [14]:
print(nd.mean(A))
print(nd.sum(A) / A.size)


[9.5]
<NDArray 1 @cpu(0)>

[9.5]
<NDArray 1 @cpu(0)>


In [15]:
x = nd.arange(4)
y = nd.ones(4)
print(x, y, nd.dot(x, y))


[0. 1. 2. 3.]
<NDArray 4 @cpu(0)> 
[1. 1. 1. 1.]
<NDArray 4 @cpu(0)> 
[6.]
<NDArray 1 @cpu(0)>


In [16]:
nd.sum(x * y)


[6.]
<NDArray 1 @cpu(0)>

In [18]:
nd.dot(A, x)


[ 14.  38.  62.  86. 110.]
<NDArray 5 @cpu(0)>

In [19]:
B = nd.ones(shape=(4, 3))
nd.dot(A, B)


[[ 6.  6.  6.]
 [22. 22. 22.]
 [38. 38. 38.]
 [54. 54. 54.]
 [70. 70. 70.]]
<NDArray 5x3 @cpu(0)>

In [20]:
nd.norm(x)


[3.7416573]
<NDArray 1 @cpu(0)>

In [21]:
nd.sum(nd.abs(x))


[6.]
<NDArray 1 @cpu(0)>